### ISSUE TITLE
Error while adding user with `-` in the name

### ISSUE THREAD

**Issue by Wei-1** [all-contributors/all-contributors-bot#292]
**Describe the bug**
The bot add @Wei instead of @Wei-1 while using the command in a PR.

**To Reproduce**
1. Go to any repo with @all-contributors bot
2. Use `@all-contributors please add Wei-1 for maintenance`
3. Check the PR created by @all-contributors bot
4. See that it add @wei instead of @Wei-1

**Expected behavior**
It should add @Wei-1 instead

**Screenshots**
https://github.com/Curt-Park/rainbow-is-all-you-need/pull/12

**Additional context**
Probably caused by `-` sign

**Comment by Curt-Park** [comment]
Fixed at https://github.com/Curt-Park/rainbow-is-all-you-need/pull/32

**Comment by marekrozmus** [comment]
@Wei-1 bot needs `@` before user name. Had same problem - check here: https://github.com/all-contributors/all-contributors-cli/issues/225#issuecomment-552918505

So you should use: Use `@all-contributors please add @Wei-1 for maintenance` and it should work correctly.

**Comment by marekrozmus** [comment]
@Wei-1 as you can see above ;)

Please somebody delete that PR :D

BTW: How did you manage to create this issue without genrating new bot PR :) ?

**Comment by Wei-1** [comment]
That's a very good question @marekrozmus I have no idea though..
btw, should we close this issue?

**Comment by Klaas-** [comment]
I think there is still an issue with "-" see this:
https://github.com/ComplianceAsCode/content/issues/5355#issuecomment-605331289
And it created https://github.com/ComplianceAsCode/content/pull/5480

**Comment by baikho** [comment]
> @Wei-1 as you can see above ;)
> 
> Please somebody delete that PR :D
> 
> BTW: How did you manage to create this issue without genrating new bot PR :) ?

I think that's because the issue / PR needs to exist before quoting the bot, see https://github.com/all-contributors/all-contributors/issues/380#issuecomment-619587900

**Comment by baikho** [comment]
I believe this needs fixing in the `parseAddComment()`, but on a side note; GitHub won't let you register such account names (anymore?) as per:

> Username may only contain alphanumeric characters or single hyphens, and cannot begin or end with a hyphen.

<img width="462" alt="Screenshot 2020-04-26 at 23 18 39" src="https://user-images.githubusercontent.com/4610533/80321373-8167ac00-8814-11ea-8a7f-9ed1a4e0a302.png">

**Comment by jakebolam** [comment]
Thank you @Wei-1

**Comment by jakebolam** [comment]
Fixed in #307

**Comment by Klaas-** [comment]
Does that make my username valuable? :) thanks for fixing @baikho
